<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>CARRENTALBUSINESS</RootNamespace>
    <AssemblyName>TRAJJ_Company</AssemblyName>
    <FileAlignment>512</FileAlignment>
	<Deterministic>true</Deterministic>
	<LangVersion>latest</LangVersion>
	<GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
	<UseWindowsForms>true</UseWindowsForms>
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	<GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="WebApp1\**" />
    <EmbeddedResource Remove="WebApp1\**" />
    <None Remove="WebApp1\**" />
    <Content Remove="WebApp1\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Data.SqlClient" Version="4.8.5" />
    <PackageReference Include="System.Resources.Extensions" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Configuration" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>