//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp1
{


    public partial class Login
    {

        /// <summary>
        /// lblError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblError;

        /// <summary>
        /// txtUsername control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtUsername;

        /// <summary>
        /// rfvUsername control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvUsername;

        /// <summary>
        /// txtPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPassword;

        /// <summary>
        /// rfvPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPassword;

        /// <summary>
        /// btnLogin control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnLogin;
    }
}
