//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp1
{


    public partial class Services
    {

        /// <summary>
        /// lblinfo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblinfo;
    }
}
