//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp1
{


    public partial class SiteMaster
    {

        /// <summary>
        /// MainContent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;

        /// <summary>
        /// phGuest control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phGuest;

        /// <summary>
        /// phUser control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phUser;

        /// <summary>
        /// litUsername control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litUsername;

        /// <summary>
        /// lbtnLogout control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton lbtnLogout;
    }
}
